MODULE FileCatalog;

REQUIRE UtilsStendex, Security;

NAMESPACE MasterData;

allowManageFileCatalog 'Разрешить управление' = DATA BOOLEAN (UserRole);
allowManageFileCatalog (User u) = GROUP SUM 1 IF allowManageFileCatalog(UserRole r) AND has(u, r);

EXTEND FORM securityPolicy
    PROPERTIES(ur) PANEL allowManageFileCatalog
;

DESIGN securityPolicy {
    roleApplicationSettings {
        tabbed = TRUE;
        NEW fileCatalogDashboard {
            caption = 'Каталог файлов';
            MOVE PROPERTY(allowManageFileCatalog(ur));
        }
    }
}

CLASS FileSystemNode 'Элемент файловой системы';
name 'Название' = DATA STRING[200] (FileSystemNode) NONULL;

parent 'Родитель' = DATA Directory (FileSystemNode);
nameParent 'Родитель' (FileSystemNode n) = name(parent(n));

dateTime 'Дата создания' = DATA DATETIME (FileSystemNode);
user 'Пользователь' = DATA User (FileSystemNode);

rootDirectory 'Корневой каталог' () = GROUP MIN Directory d IS Directory IF NOT parent(d);

CLASS Directory 'Каталог' : FileSystemNode;

catalogAccessRole 'Разрешить управление' = DATA BOOLEAN (UserRole, Directory);
catalogAccessRole (User u, FileSystemNode n) = GROUP SUM 1 IF catalogAccessRole(UserRole r, IF n IS File THEN parent(n) ELSE n) AND has(u, r);

CONSTRAINT Directory d = parent(d) CHECKED BY parent[Directory] MESSAGE 'Каталог не может быть родителем самого себя!';

level 'Уровень' (FileSystemNode child, FileSystemNode parent) =
    RECURSION 1l IF child IS FileSystemNode AND parent = child
        STEP 2l IF parent = parent($parent) MATERIALIZED;

CONSTRAINT level(parent(Directory d), d) MESSAGE 'Нельзя установить родителя, который уже является вложенной папкой!';

WHEN CHANGED(catalogAccessRole(UserRole r , Directory d)) DO {
    FOR level(Directory d1, d) DO catalogAccessRole(r , d1) <- catalogAccessRole(r, d);
}

CLASS File 'Файл' : FileSystemNode;
file 'Файл' = DATA RAWFILE (File) NONULL;
extension 'Расширение' = DATA STRING[10] (File);

nodeName 'Название элемента' (FileSystemNode n) = CONCAT '.', name(n), IF n IS File THEN extension(n);

WHEN SET(FileSystemNode n IS FileSystemNode) DO {
    dateTime(n) <- currentDateTime();
    user(n) <- currentUser();
}

FORM fileSystemNodes 'Элементы файловой системы'
    OBJECTS n = FileSystemNode
    PROPERTIES READONLY nodeName(n)
    
    LIST FileSystemNode OBJECT n
;

previewPdfFile = DATA LOCAL NESTED PDFFILE();
previewImageFile = DATA LOCAL NESTED IMAGEFILE();

uploadFile 'Загрузить' (File f) {
    INPUT uf = NAMEDFILE DO {
        file(f) <- RAWFILE(uf);
        name(f) <- name(uf);
        extension(f) <- extension(uf);
    }
} IMAGE 'upload.png';

FORM directory 'Каталог'
    OBJECTS d = Directory PANEL
    PROPERTIES name(d), nameParent(d)

    OBJECTS r = UserRole
    PROPERTIES name(r), catalogAccessRole(r, d) 

    EVENTS ON APPLY BEFORE {
        IF (NOT PREV(catalogAccessRole(currentUser(), d)) OR NOT catalogAccessRole(currentUser(), d))
            AND NOT allowManageFileCatalog(currentUser()) THEN {
            MESSAGE 'У вас нет прав на редактирование этого каталога!';
            beforeCanceled() <- TRUE;
        }
    }

    EVENTS ON OK BEFORE {
        IF NOT name(d) THEN {
            MESSAGE 'Название каталога не может быть пустым!';
            beforeCanceled() <- TRUE;
        }
    }

    EVENTS ON CLOSE { name(d) <- NULL; }
    
    EDIT Directory OBJECT d
;

DESIGN directory {
    OBJECTS {
        NEW pane {
            fill = 1;
            horizontal = TRUE;
            NEW catalogDetails {
                fill = 1;
                MOVE PROPERTY(name(d));
                MOVE PROPERTY(nameParent(d));
            }
            NEW rolesPanel {
                fill = 1;
                MOVE BOX(r);
            }
        }
    }
}

FORM file 'Файл'
    OBJECTS f = File PANEL
    PROPERTIES uploadFile(f)
    PROPERTIES (f) name, nameParent

    EVENTS ON APPLY BEFORE {
        IF (NOT PREV(catalogAccessRole(currentUser(), parent(f))) OR NOT catalogAccessRole(currentUser(), parent(f)))
            AND NOT allowManageFileCatalog(currentUser()) THEN {
            MESSAGE 'У вас нет прав на редактирование этого файла!';
            beforeCanceled() <- TRUE;
        }
    }
    
    EVENTS ON OK BEFORE {
        IF NOT name(f) THEN {
            MESSAGE 'Название файла не может быть пустым!';
            beforeCanceled() <- TRUE;
        }
        ELSE IF NOT file(f) THEN {
            MESSAGE 'Файл не загружен!';
            beforeCanceled() <- TRUE;
        }
    }
    
    EVENTS ON CLOSE { name(f) <- NULL; }

    EDIT File OBJECT f
;

newFile 'Добавить файл' (FileSystemNode n) {
    NEW f = File {
        parent(f) <- IF n IS File THEN parent(n) ELSE n;
        SHOW file OBJECTS f = f;
        IF NOT name(f) THEN DELETE f;
        APPLY;
    }
} IMAGE 'add.png' CHANGEKEY 'INSERT';

createDirectory 'Добавить каталог' (FileSystemNode n) {
    NEW d = Directory {
        parent(d) <- IF n IS File THEN parent(n) ELSE n;
        FOR has(currentUser(), UserRole r) DO catalogAccessRole(r, d) <- TRUE;
        SHOW directory OBJECTS d = d;
        IF NOT name(d) THEN DELETE d;
        APPLY;
    }
} IMAGE 'add.png';

createRootDirectory 'Добавить каталог' () {
    NEW d = Directory {
        FOR has(currentUser(), UserRole r) DO catalogAccessRole(r, d) <- TRUE;
        SHOW directory OBJECTS d = d;
        IF NOT name(d) THEN DELETE d;
        APPLY;
    }
} IMAGE 'add.png';

editObject 'Редактировать' (FileSystemNode n) {
    NEWSESSION { IF n IS File THEN SHOW file OBJECTS f = n NOWAIT DOCKED; ELSE SHOW directory OBJECTS d = n NOWAIT DOCKED; }
}

//deleteNode 'Удалить' (FileSystemNode n) {
//    ASK CONCAT '', 'Вы уверены, что хотите удалить "', nodeName(n), '"?' DO {
//        NEWSESSION DELETE n;
//        APPLY;
//    }
//} IMAGE 'delete.png';

findNode = DATA LOCAL FileSystemNode;
nameFindNode 'Название элемента' = nodeName(findNode());

open 'Скачать' (FileSystemNode f) { IF f IS File THEN open(file(f), nodeName(f)); } IMAGE 'open.png';

FORM fileCatalog 'Каталог файлов'
    TREE catalog n = FileSystemNode PARENT parent(n)
    PROPERTIES READONLY nodeName(n) ON CONTEXTMENU editObject(n)
    PROPERTIES TOOLBAR open(n) SHOWIF n IS File 
    PROPERTIES TOOLBAR SHOWIF allowManageFileCatalog(currentUser()) OR catalogAccessRole(currentUser(), n) createDirectory(n), newFile(n)
    PROPERTIES TOOLBAR createRootDirectory() SHOWIF NOT rootDirectory()
    PROPERTIES READONLY previewPdfFile() SHOWIF previewPdfFile(), previewImageFile() SHOWIF NOT previewPdfFile()
    PROPERTIES nameFindNode()
    PROPERTIES(n) NEWSESSION DELETE
    FILTERS (n = findNode() OR level(findNode(), n)) OR NOT findNode()
    
    EVENTS ON CHANGE n {
        previewPdfFile() <- NULL;
        previewImageFile() <- NULL;
        IF n IS File THEN {
            IF lower(extension(n)) = 'jpg' OR lower(extension(n)) = 'jpeg' OR lower(extension(n)) = 'png' OR lower(extension(n)) = 'bmp' THEN {
                previewImageFile() <- IMAGEFILE(file(n));
            }
            IF lower(extension(n)) = 'pdf' THEN {
                previewPdfFile() <- PDFFILE(file(n));
            }
            IF lower(extension(n)) = 'doc' OR lower(extension(n)) = 'docx' THEN {
                TRY { wordToPdf(file(n)); } CATCH {}
                previewPdfFile() <- exportPdfFile();
            }
        }
    }
;

DESIGN fileCatalog {
    OBJECTS {
        NEW main {
            fill = 1;
            horizontal = TRUE;
            NEW catalog {
                fill = 1;
                MOVE BOX(TREE catalog) { caption = ''; }
                PROPERTY(nodeName(n)) { font = IF n IS Directory THEN 'bold'; }
            }
            NEW filterAndPreview {
                fill = 1;
                NEW filter {
                    fill = 1;
                    horizontal = TRUE;
                    MOVE PROPERTY(nameFindNode());
                }
                NEW preview {
                    fill = 1000;
                    MOVE PROPERTY(previewImageFile()) { fill = 1; size = (100, 100); caption = ''; }
                    MOVE PROPERTY(previewPdfFile()) { fill = 1; size = (100, 100); caption = ''; }
                }
            }
        }
    }
}

NAVIGATOR {
    dashboard {
        NEW fileCatalog;
    }
}