MODULE FileManager;

REQUIRE UtilsStendex, Security, Category;

NAMESPACE MasterData;

CLASS FileSystemNode 'Элемент файловой системы';
name 'Название' = DATA STRING[200] (FileSystemNode);
parentN 'Родитель' = DATA Directory (FileSystemNode);
dateTime 'Дата создания' = DATA DATETIME (FileSystemNode);
user 'Пользователь' = DATA User (FileSystemNode);

rootDirectory 'Корневой каталог' () = GROUP MIN Directory d IS Directory IF NOT parentN(d);

nameParent 'Родитель' (FileSystemNode n) = name(parentN(n));

CLASS Directory 'Каталог' : FileSystemNode;
CONSTRAINT Directory n = parentN(n) CHECKED BY parentN MESSAGE 'Каталог не может быть родителем самого себя!';

CLASS File 'Файл' : FileSystemNode;
file 'Файл' = DATA RAWFILE (File);
extension 'Расширение' = DATA STRING[10] (File);

nodeName 'Название элемента' (FileSystemNode n) = CONCAT '.', name(n), IF n IS File THEN extension(n);

WHEN SET(FileSystemNode n IS FileSystemNode) DO {
    dateTime(n) <- currentDateTime();
    user(n) <- currentUser();
}

previewPdfFile = DATA PDFFILE ();
previewImageFile = DATA IMAGEFILE ();

uploadFile 'Загрузить' (File f) {
    INPUT uf = NAMEDFILE DO {
        file(f) <- RAWFILE(uf);
        name(f) <- name(uf);
        extension(f) <- extension(uf);
    }
} IMAGE 'upload.png';

FORM directory 'Папка'
    OBJECTS n = Directory PANEL
    PROPERTIES (n) name, nameParent
    
    EDIT Directory OBJECT n
;

FORM file 'Файл'
    OBJECTS f = File PANEL
    PROPERTIES uploadFile(f)
    PROPERTIES (f) name, nameParent

    EDIT File OBJECT f
;

newFile 'Добавить файл' (FileSystemNode n) {
    NEW f = File {
        parentN(f) <- IF n IS File THEN parentN(n) ELSE n;
        SHOW file OBJECTS f = f;
        }
} IMAGE 'add.png' CHANGEKEY 'INSERT' HIDE;

createDirectory 'Добавить папку' (FileSystemNode n) {
    NEW d = Directory {
        parentN(d) <- IF n IS File THEN parentN(n) ELSE n;
        SHOW directory OBJECTS n = d;
    }
} IMAGE 'add.png';

createRootDirectory 'Добавить папку' () {
    NEW d = Directory {
        SHOW directory OBJECTS n = d;
    }
} IMAGE 'add.png';

FORM fileManager 'Каталог файлов'
    TREE catalog n = FileSystemNode PARENT parentN(n)
    PROPERTIES READONLY nodeName(n)
    PROPERTIES (n) DELETE
    PROPERTIES TOOLBAR createDirectory(n), newFile(n), createRootDirectory() SHOWIF NOT rootDirectory()
    PROPERTIES () READONLY previewPdfFile SHOWIF previewPdfFile(), previewImageFile SHOWIF NOT previewPdfFile()

    EVENTS ON CHANGE n {
        previewPdfFile() <- NULL;
        previewImageFile() <- NULL;
        IF n IS File THEN {
            IF lower(extension(n)) = 'jpg' OR lower(extension(n)) = 'jpeg' OR lower(extension(n)) = 'png' OR lower(extension(n)) = 'bmp' THEN {
                previewImageFile() <- IMAGEFILE(file(n));
            }
            IF lower(extension(n)) = 'pdf' THEN {
                previewPdfFile() <- PDFFILE(file(n));
            }
            IF lower(extension(n)) = 'doc' OR lower(extension(n)) = 'docx' THEN {
                TRY { wordToPdf(file(n)); } CATCH {}
                previewPdfFile() <- exportPdfFile();
            }
        }
    }
;

DESIGN fileManager {
    OBJECTS {
        NEW pane {
            fill = 1;
            horizontal = TRUE;
            NEW catalog {
                fill = 1;
                MOVE BOX(TREE catalog) { caption = ''; };
            }
            NEW preview {
                fill = 1;
                MOVE PROPERTY(previewImageFile()) { fill = 1; caption = ''; };
                MOVE PROPERTY(previewPdfFile()) { fill = 1; caption = ''; };
            }
        }
    }
}

NAVIGATOR {
    dashboard {
        NEW fileManager;
    }
}