MODULE TaskNotificationStendex;

REQUIRE ProjectTask, NotificationsStendex, TaskCustom, DrawingSchedule;

NAMESPACE ProjectManagement;

CLASS TaskNotification 'Уведомления о задачах';

task = DATA Task (TaskNotification);

employeeToNotify = DATA Employee(TaskNotification);
nameEmployeeToNotify 'Кого уведомить' (TaskNotification tn) = name[CustomUser](employeeToNotify(tn));
dateTimeNotification 'Дата и время' = DATA DATETIME (TaskNotification) CHARWIDTH 15;
countNotifications(Task t) = GROUP SUM 1 IF task(TaskNotification tn) = t;
notificationSent 'Отправлено' = DATA BOOLEAN (TaskNotification) CHARWIDTH 10;
note 'Примечание' = DATA STRING (TaskNotification) CHARWIDTH 20;
repeatable 'Повторяющееся' = DATA BOOLEAN (TaskNotification) CHARWIDTH 10;

EXTEND FORM task
    OBJECTS tn = TaskNotification
    PROPERTIES(tn) DISABLEIF notificationSent(tn) nameEmployeeToNotify, dateTimeNotification, note, notificationSent READONLY
    PROPERTIES(tn) repeatable BEFORE notificationSent(tn)
    PROPERTIES(tn) NEW, DELETE
    FILTERS task(tn) = t
;

DESIGN task {
    details {
        MOVE BOX (tn) { caption = 'Уведомления'; }
    }
}

notificationMessage (TaskNotification tn) = JSON FROM title = ('Напоминание по задаче "' + name(task(tn)) + '"'), 
    options = JSON FROM 
        body = OVERRIDE note(tn), (CONCAT ', ', 'Исполнитель: ' + nameAssignedTo(task(tn)), 'проект: ' + nameProject(task(tn)), 'приоритет: ' + namePriority(task(tn)), 
            'дедлайн: ' + toChar(deadline(task(tn)), 'dd.mm.yyyy hh:mm'))
;

notificationMessageSimple (TaskNotification tn) = CONCAT '\n', 'Напоминание по задаче "' + name(task(tn)) + '"' + '\n', 'исполнитель: ' + nameAssignedTo(task(tn)), 'проект: ' + nameProject(task(tn)), 'приоритет: ' + namePriority(task(tn)),
    'дедлайн: ' + toChar(deadline(task(tn)), 'dd.mm.yyyy hh:mm'), 'примечание: ' + note(tn);

WHEN LOCAL FORMS task SET (TaskNotification tn IS TaskNotification) DO {
    employeeToNotify(tn) <- assignedTo(task(tn));
    dateTimeNotification(tn) <- currentDateTime();
}

showTask 'Открыть задачу' (Task t) {
    SHOW task OBJECTS t = t DOCKED;
}

showTaskId 'Открыть задачу' (LONG id) {
    FOR LONG(Task t AS Task) = id DO 
        SHOW task OBJECTS t = t DOCKED;
}

dontNotifyMe 'Больше не уведомлять' (Task t) {
    dontNotify(t) <- TRUE;
    APPLY;
}

FORM openTask 'Уведомление'
    OBJECTS s = STRING PANEL
    PROPERTIES READONLY notifi = TEXT(s)

    OBJECTS t = Task
    PROPERTIES(t) showTask
    PROPERTIES(t) NEWSESSION dontNotifyMe DISABLEIF dontNotify(t)
;

DESIGN openTask {
    size = (330, 270);
    BOX(t) { caption = ''; }
    BOX(s) { caption = ''; }
    OBJECTS {
        MOVE PROPERTY(notifi);
        PROPERTY(notifi) { caption = ''; alignment = STRETCH; valueHeight = 150; valueWidth = 300; }
    }
    MOVE PANEL AFTER OBJECTS {
        NEW vert {
            fill = 1;
            horizontal = FALSE;
            MOVE PROPERTY (dontNotifyMe(t)) { alignment = STRETCH; }
            NEW horiz {
                fill = 1;
                horizontal = TRUE;
                MOVE PROPERTY(showTask(t)) { alignment = STRETCH; fill = 1; };
                MOVE PROPERTY(formClose()) LAST { alignment = STRETCH; fill = 1; };
            }
        }
        
    }
    REMOVE TOOLBAR;
    REMOVE TOOLBARLEFT;
    REMOVE PROPERTY(formOk());
    REMOVE PROPERTY(formRefresh());
}

notifyUsers () {
    FOR Connection c IS Connection AND connectionStatus(c) = ConnectionStatus.connectedConnection DO {
        FOR TaskNotification tn IS TaskNotification AND user(c) = employeeToNotify(tn) AND currentDateTime() >= dateTimeNotification(tn)
            AND (NOT notificationSent(tn) OR repeatable(tn)) AND NOT dontNotify(task(tn)) AND NOT closed(task(tn)) DO {
            IF pushConnection(employeeToNotify(tn)) THEN {
                IF sendNotificiationInsteadMessage() THEN {
                    NEWTHREAD {
                        SHOW task OBJECTS t = task(tn) DOCKED NOWAIT;
                    } TO exportInteger;
                    pushNotify(pushConnection(employeeToNotify(tn)), notificationMessage(tn), action(exportInteger()));
                } ELSE {
                    NEWSESSION {
                        NEWTHREAD {
                            SHOW openTask OBJECTS t = task(tn), s = notificationMessageSimple(tn) FLOAT;
                        } CONNECTION c;
                    }
                }
            }
            notificationSent(tn) <- TRUE;
            APPLY;
        }
    }
}

subject = ABSTRACT VALUE ISTRING (Task);
subject (Task t) += CONCAT ' - ', (CONCAT ' ', '(' + nameStatus(t) + ')', idName(t));

propertiesHtmlShortList (Task t) = HTMLTEXT(CONCAT '', '<b>Напоминание по задаче "' + name(t) + '"' + '</b>',
                                                                   '<p>Исполнитель: ' + nameAssignedTo(t) + '</p>', 
                                                                   '<p>Проект: ' + nameProject(t) + '</p>', 
                                                                   '<p>Приоритет: ' + namePriority(t) + '</p>',
                                                                   '<p>Дедлайн: ' + toChar(deadline(t), 'dd.mm.yyyy hh:mm')) + '</p>';

info = ABSTRACT VALUE HTMLTEXT (Task);
info (Task t) += propertiesHtmlShortList(t);

body = ABSTRACT VALUE HTMLTEXT (Task);
body(Task t) += HTMLTEXT (CONCAT '',
    '<h1><a href="' + contextUrl('/exec/ProjectManagement.showTaskId?id=' + t) + '">' + subject(t) + '</a></h1>',
    info(t),
    description(t)
    );

notifyUserEmail 'Уведомление на почту' (TaskNotification tn)  {
    EMAIL
        SUBJECT 'Напоминание по задаче "' + name(task(tn)) + '"'
        TO email[Contact](employeeToNotify(tn))
        BODY body(task(tn));
    IF canceled() THEN RETURN;
    ;
}

WHEN SET(TaskNotification tn IS TaskNotification) AND (NOT notificationSent(tn) OR repeatable(tn)) AND NOT dontNotify(task(tn)) AND NOT closed(task(tn)) DO {
    notifyUserEmail(tn);
}

FORM taskNotifications 'Журнал уведомлений'
    OBJECTS dates = (from = DATETIME, to = DATETIME ) PANEL
    PROPERTIES valFrom = VALUE (from), valTo = VALUE (to)

    OBJECTS tn = TaskNotification LAST
    PROPERTIES(tn) READONLY 'Имя пользователя' = nameEmployeeToNotify, note, 'Дата и время уведомления' = dateTimeNotification
    FILTERS notificationSent(tn)
    FILTERS dateTimeNotification(tn) >= from AND dateTimeNotification(tn) <= to
    EVENTS
        ON INIT {
            SEEK taskNotifications.dates OBJECTS from = dateTimeToDateTime(currentDate(), 00:00), to = currentDateTime();
        }
;

NAVIGATOR {
    logs {
        NEW taskNotifications;
    }
}

WHEN SETCHANGED(assignedTo(Task t)) AND (author(t) != assignedTo(t) OR NOT author(t)) DO {
    NEW tn = TaskNotification {
        task(tn) <- t;
        employeeToNotify(tn) <- assignedTo(task(tn));
        dateTimeNotification(tn) <- currentDateTime();
        repeatable(tn) <- TRUE;
    }
}

EXTEND FORM taskDrawing
    OBJECTS tn = TaskNotification
    PROPERTIES(tn) DISABLEIF notificationSent(tn) nameEmployeeToNotify, dateTimeNotification, note, notificationSent READONLY
    PROPERTIES(tn) repeatable BEFORE notificationSent(tn)
    PROPERTIES(tn) NEW, DELETE
    FILTERS task(tn) = t
;

DESIGN taskDrawing {
    header {
        NEW details {
            tabbed = TRUE;
            fill = 1;
            MOVE BOX (tn) { caption = 'Уведомления'; }
            REMOVE TOOLBARSYSTEM (tn);
        }
    }
}

WHEN LOCAL FORMS taskDrawing SET (TaskNotification tn IS TaskNotification) DO {
    employeeToNotify(tn) <- assignedTo(task(tn));
    dateTimeNotification(tn) <- currentDateTime();
}

