MODULE TaskCustom;

REQUIRE Task, TaskType, UtilsStendex;

NAMESPACE ProjectManagement;

color 'Цвет' = DATA COLOR (TaskStatus);

EXTEND FORM options
    PROPERTIES (ts) color
;

onStarted() + {
    IF NOT taskType('default') THEN {
        NEW t = TaskType {
            name(t) <- 'По умолчанию';
            id(t) <- 'default';
        }
    }
}

WHEN LOCAL SET (Task t IS Task) AND NOT type(t) DO type(t) <- taskType('default');

NAVIGATOR {
    dashboard{
        MOVE tasks;
    }
}

dontNotify 'Не уведомлять' = DATA BOOLEAN (Task);

EXTEND FORM task
    PROPERTIES (t) dontNotify
;

EXTEND FORM tasks
    PROPERTIES (t) dontNotify
;

DESIGN task {
    header {
        MOVE PROPERTY (dontNotify(t));
    }
}

EXTEND FORM tasks
    OBJECTS tc = Task CALENDAR BACKGROUND rgbColorPriority(tc)

    PROPERTIES(tc) READONLY id, name
    PROPERTIES READONLY PANEL pcname = name(tc), nameAuthor = nameAuthor(tc), nameAssignedTo = nameAssignedTo(tc),
        nameStatus = nameStatus(tc), ptype = nameType(tc), namePriority = namePriority(tc)
    PROPERTIES(tc) NEWSESSION NEW, pedit = EDIT, pdelete = DELETE

    FILTERS [FILTER tasks.t](tc)
;

@defineDocFilter(tasks, task, TaskType, type, tc, 'Type', type);
@defineDocFilter(tasks, task, Employee, assignedTo, tc, 'Assigned to', assignedTo);

DESIGN tasks {
    tabbedPane {
        MOVE BOX(tc) FIRST {
            caption = 'Календарь';
            GRID(tc) {
                MOVE PROPERTY(pcname);
                MOVE PROPERTY(ptype);
                MOVE PROPERTY(namePriority);
                MOVE PROPERTY(nameAuthor);
                MOVE PROPERTY(nameAssignedTo);
                MOVE PROPERTY(nameStatus);
                NEW panelActions {
                    horizontal = TRUE;
                    alignment = STRETCH;
                    MOVE PROPERTY(pedit) { fill = 1; };
                    MOVE PROPERTY(pdelete) { fill = 1; };
                }
            }
        }
    }
}