MODULE EmployeeNotificationContactStendex;

REQUIRE Contacts, EmployeeNotificationStendex, NotificationsStendex;

NAMESPACE Notifications;

EXTEND CLASS TypeEmailNotification {
    contactReminder 'Напоминание (Контакты)'
}

sentDateTimeMail 'Отправлено уведомление по почте'  = DATA DATETIME (TypeEmailNotification, Contacts);
sentDateTimeNotification 'Отправлено уведомление' = DATA DATETIME (Contacts);

needSendNotifications = DATA BOOLEAN(Contacts);

WHEN SETCHANGED(Contacts c IS Contacts) DO needSendNotifications(c) <- TRUE;

condionSendEmail = ABSTRACT VALUE BOOLEAN (TypeEmailNotification, Contacts);
condionSendNotification = ABSTRACT VALUE BOOLEAN (Contacts);

condionSendEmail(TypeEmailNotification en, Contacts c) += needSendNotifications(c) AND NOT sendNotificiationInsteadMessage()
    AND notifite(TypeEmailNotification.contactReminder, manager(c)) AND NOT sentDateTimeMail(en, c) AND reminder(c);
condionSendNotification(Contacts c) += needSendNotifications(c) AND NOT sentDateTimeNotification(c) AND reminder(c);

bodyNotificationContact (Contacts c) = CONCAT '\n', 'Напоминание о контакте с ' + nameExhibition(c), 'Контрагент ' + nameOrganizer(c), 
    'Контакты ' + phoneNumber(c), 'Комментарий ' + comment(c), 'Дата взаимодействия ' + date(c);

sendEmailNotificationContact 'Отправить' (TypeEmailNotification en, Contacts c) {
    EMAIL
        SUBJECT (CONCAT  ' ', 'Напоминание о выставке ' + nameExhibition(c), 'Контрагент ' + nameOrganizer(c))
        TO email(en, manager(c))
        BODY bodyNotificationContact(c);
    APPLY;
    IF canceled() THEN RETURN;

    sentDateTimeMail(en, c) <- currentDateTime();
    APPLY;
}

sendNotificationContact 'Отправить уведомление контакт' (Contacts c) {
    FOR Connection con IS Connection AND connectionStatus(con) = ConnectionStatus.connectedConnection
        AND user(con) = manager(c) DO {
        IF pushConnection(manager(c)) THEN {
            NEWSESSION {
                NEWTHREAD {
                    SHOW contactNotification OBJECTS s = bodyNotificationContact(c) FLOAT;//
                    sentDateTimeNotification(c) <- currentDateTime();
                    APPLY;
                } CONNECTION con;
            }
        }
    }
}

sendNotification (DATETIME dTFrom) +{
    FOR reminder(Contacts c) >= dTFrom AND reminder(c) <= currentDateTime() AND condionSendNotification(c) DO {
        sendNotificationContact(c);
    }
}

sendEmailNotification(DATE dFrom) + {
    FOR toDate(reminder(Contacts c)) >= dFrom AND toDate(reminder(c)) <=currentDate() AND condionSendEmail(TypeEmailNotification.contactReminder, c) DO 
        {sendEmailNotificationContact(TypeEmailNotification.contactReminder, c);}
}