MODULE ProductStendex;

REQUIRE Product;

NAMESPACE MasterData;

FORM dialogProduct '{Product}'
    OBJECTS p = Product PANEL
    PROPERTIES(p) name, canonicalNameCategory, nameUom
;

DESIGN dialogProduct {
    caption = badged(name(p), class(p));
    OBJECTS {        
        NEW header {            
            MOVE PROPERTY(name(p)) { alignment = STRETCH;}
            MOVE PROPERTY(canonicalNameCategory(p));
            MOVE PROPERTY(nameUom(p));
            
        }        
    }
}