MODULE NotificationsStendex;

REQUIRE PurchaseOrderStendex, Chat, System;

NAMESPACE Notifications;

chatOrderNotification = DATA Chat ();
nameChatOrderNotification 'Чат уведомлений по заказам' = name(chatOrderNotification());
EXTEND FORM System.options
    PROPERTIES nameChatOrderNotification()
;
DESIGN System.options{
    pane{
        NEW notification{
            caption = 'Уведомления';
            MOVE PROPERTY (nameChatOrderNotification());
        }
    }   
}

sendNotification 'Отправить уведомление' (DATETIME dateTimeNotification) ABSTRACT LIST;

messageNotification (Order o) = CONCAT '\n', 'Новый заказ', '№' + number(o), 'Поставщик ' + nameVendor(o), 'Сумма ' + amount(o);   

WHEN SET(Order o IS Order) AND number(o) AND chatOrderNotification() DO{
    sendMessage(chatOrderNotification(), messageNotification(o), NULL, TRUE);
}

sendNotificiationInsteadMessage 'Отправлять уведомления вместо сообщений' = DATA BOOLEAN ();
EXTEND FORM System.options PROPERTIES sendNotificiationInsteadMessage();

DESIGN System.options {
    notification {
        MOVE PROPERTY(sendNotificiationInsteadMessage()) FIRST;
        PROPERTY(sendNotificiationInsteadMessage()) { panelCaptionLast = FALSE; }
    }
}