MODULE DrawingSchedule;

REQUIRE ProjectTask, TimesheetSupervisor, UtilsStendex, ProjectStendex, Employee, TaskCustom, EnterpriseData;

NAMESPACE ProjectManagement;

designer 'Дизайнер' = DATA Individual (Task);
nameDesigner 'Дизайнер' (Task t) = name(designer(t));

CONSTRAINT SETCHANGED(designer(Task t)) AND NOT isDesigner(designer(t)) CHECKED BY designer[Task] 
    MESSAGE 'Выбранное физ.лицо не является дизайнером.'
;

color 'Цвет' (Task t) = color(status(t));

taskStartDate 'Дата начала задачи' = DATA DATE (Task);
taskEndDate 'Дата окончания задачи' = DATA DATE (Task);

isDrawing (Task t) = id(type(t)) = 'typeDrawing';

FORM taskDrawing '{Task}'
    OBJECTS t = Task PANEL
    PROPERTIES(t) 'Наименование' = name, nameStatus, nameAuthor, 'Менеджер' = nameAssignedTo, nameProject, nameDesigner, taskStartDate, taskEndDate
    PROPERTIES inputComment(), newComment(t)

    OBJECTS cmt = TaskComment CUSTOM 'comments'
    PROPERTIES id = VALUE(cmt)
    PROPERTIES(cmt) nameUser, dateTime, text
    PROPERTIES(cmt) edit ON CHANGE {
        SHOW editTaskComment OBJECTS c = cmt;
    },
        delete = DELETE
    ORDERS id DESC
    FILTERS task(cmt) = t
;

DESIGN taskDrawing {
    OBJECTS {
        NEW pane {
            fill = 1;
            horizontal = TRUE;
            NEW header {
                NEW main {
                    horizontal = TRUE;
                    alignment = STRETCH;
                    MOVE PROPERTY(name(t)) { flex = 1; fontSize = 16; }
                }
                NEW pro {
                    horizontal = TRUE;
                    alignment = STRETCH;
                    MOVE PROPERTY(nameProject(t)) { flex = 1; fontSize = 16; }
                }
                NEW params {
                    lines = 2;
                    alignment = STRETCH;
                    MOVE PROPERTY(nameStatus(t));
                    MOVE PROPERTY(nameAuthor(t));
                    MOVE PROPERTY(nameAssignedTo(t));
                    MOVE PROPERTY(taskStartDate(t));
                    MOVE PROPERTY(nameDesigner(t));
                    MOVE PROPERTY(taskEndDate(t));
                }
            }
            NEW comments {
                fill = 1;
                caption = badged('Comments', countComment(t));
                NEW inputComment {
                    horizontal = TRUE;
                    alignment = STRETCH;
                    MOVE PROPERTY(inputComment()) {
                        valueHeight = -1;
                        fill = 1;
                    }
                    MOVE PROPERTY(newComment(t)) {
                        alignment = STRETCH;
                    }
                }
                MOVE GRID(cmt) {
                    height = 200;
                    width = 400;
                    fill = 1;
                }
                REMOVE BOX(cmt);
            }
        }
    }
}

CLASS DrawingScheduleLine;

phone 'Телефон' = DATA STRING (DrawingScheduleLine) CHARWIDTH 15;
project 'Проект' = DATA Project (DrawingScheduleLine) NONULL;
name 'Проект' (DrawingScheduleLine l) = name(project(l));

manager 'Менеджер' = DATA Employee (DrawingScheduleLine) NONULL;
managerName 'Менеджер' (DrawingScheduleLine l)= MasterData.name(manager(l));

designer 'Дизайнер' = DATA Individual (DrawingScheduleLine) NONULL;
designerName 'Дизайнер' (DrawingScheduleLine l)= MasterData.name(designer(l));

nameTask(DATE d, DrawingScheduleLine l) = OVERRIDE( 
    GROUP CONCAT name(Task t) IF d >= taskStartDate(t) 
        AND d <= taskEndDate(t) 
        AND designer(l) = designer(t) 
        AND project(t) = project(l) 
        AND assignedTo(t) = manager(l), 
        ', ' ORDER name(t)), ' ';

color 'Задачи' (DATE d, DrawingScheduleLine l) = 
    GROUP MAX color(Task t) IF d >= taskStartDate(t) AND d <= taskEndDate(t) AND designer(l) = designer(t) AND project(t) = project(l) AND assignedTo(t) = manager(l);
colorTask(DATE dt, Task t) = GROUP MAX color(status(t)) IF dt >= taskStartDate(t) AND dt <= taskEndDate(t);

nameTypeTask(DrawingScheduleLine l)= GROUP MAX nameType(Task t) IF id(type(t)) = ('typeDrawing') AND l IS DrawingScheduleLine;

FORM taskDateEmployee 'Задачи'
    OBJECTS i = INTERVAL[DATE] PANEL
    OBJECTS l = DrawingScheduleLine PANEL

    OBJECTS t = Task
    PROPERTIES(t) nameType, name, nameProject
    PROPERTIES(t) taskStartDate, taskEndDate, color, nameDesigner, nameAssignedTo
    PROPERTIES(t) NEW, EDIT, DELETE
    FILTERS nameType(t) = nameTypeTask(l), project(t) = project(l), designer(t) = designer(l), assignedTo(t) = manager(l)
;

task (DATE date, Project p, Individual d, Employee m) = GROUP MAX Task t IF isDrawing(t) AND 
    project(t) = p AND designer(t) = d AND assignedTo(t) = m
    AND date >= taskStartDate(t) AND date <= taskEndDate(t)
;
countTask (DATE date, Project p, Individual d, Employee m) = GROUP SUM 1 IF isDrawing(Task t) AND
    project(t) = p AND designer(t) = d AND assignedTo(t) = m
    AND date >= taskStartDate(t) AND date <= taskEndDate(t)
;
countTask (DATE date, Task t) = GROUP SUM 1 IF isDrawing(Task tt)
    AND date >= taskStartDate(tt) AND date <= taskEndDate(tt) AND tt = t
;

comment 'Комментарий'(INTERVAL[DATE] int, Project p, Individual d, Employee m) = 
    OVERRIDE (GROUP CONCAT name(Task t) IF project(t) = p AND designer(t) = d AND assignedTo(t) = m  AND  taskStartDate(t) >= from(int) AND taskEndDate(t) <= to(int)
    , ' ' ORDER t), ' '
;
captionTask(DATE date, Project p, Individual d, Employee m) = ' ' IF countTask(date, p, d, m);
captionTask(DATE date, Task t) = ' ' IF countTask(date, t);

inPeriod (INTERVAL[DATE] int, Project p, Individual d, Employee m) = 
    GROUP SUM 1 IF task(DATE date, p, d, m) AND iterate(date, from(int), to(int));
inPeriod(INTERVAL[DATE] int, Task t) = GROUP SUM 1 IF countTask(DATE dt, t) AND iterate(dt, from(int), to(int));

showTask 'Добавить задачу' (INTERVAL[DATE] int)  {
    NEWSESSION SHOW taskDateEmployee OBJECTS i = int;
} ASON CONTEXTMENU nameTask[DATE, DrawingScheduleLine];

fio (Employee e) = CONCAT ' ', lastName[Contact](e), initials(e);

FORM drawingSchedule 'График отрисовки'
    OBJECTS dates = INTERVAL[DATE] PANEL NULL
    PROPERTIES dates '' = VALUE(dates)

    OBJECTS d = DATE
    FILTERS iterate(d, from(dates), to(dates))

    OBJECTS tt = Task
    PROPERTIES READONLY pro = nameProject(tt), man 'Менеджер' = nameAssignedTo(tt), des = nameDesigner(tt), 'Наименование' = name(tt)
    PROPERTIES captionTask(d, tt) DRAW tt COLUMNS (d) HEADER extractDay(d) BACKGROUND colorTask(d, tt)
    PROPERTIES (tt) NEWSESSION edit TOOLBAR 
    FILTERS inPeriod(dates, tt)
    FILTERS isDrawing(tt)
    
    OBJECTS s = TaskStatus
    PROPERTIES READONLY color = ' ' IF color(s) COLUMNS (s) HEADER name(s) BACKGROUND (color(s)) PANEL 
    FILTERS color(s)
    
    EVENTS ON INIT {
        SEEK drawingSchedule.dates = interval(firstDayOfMonth(currentDate()), lastDayOfMonth(currentDate()));
    }
    PROPERTIES prevInterval '<' = { SEEK drawingSchedule.dates = prevMonthInterval(dates); },
        nextInterval '>' = { SEEK drawingSchedule.dates = nextMonthInterval(dates); }
;

newDrawingTask 'Добавить'(){
    NEW t = Task{
        type(t) <- taskType('typeDrawing');
        author(t) <- currentUser();
        taskStartDate(t) <- currentDate();
        taskEndDate(t) <- currentDate();
        SHOW taskDrawing OBJECTS t = t DOCKED;
    }
} IMAGE 'add.png';

EXTEND FORM tasks
    PROPERTIES NEWSESSION 'Добавить отрисовку' = newDrawingTask()
;

DESIGN tasks {
    TOOLBARRIGHT(t) {
        MOVE PROPERTY(newDrawingTask()) FIRST;
    }
}

EXTEND FORM drawingSchedule
    OBJECTS t = Task
    PROPERTIES(t) READONLY  nameType, name, nameProject, nameStatus BACKGROUND color(t)
    PROPERTIES(t) READONLY taskStartDate, taskEndDate, nameDesigner, 'Менеджер' = nameAssignedTo
    FILTERS taskStartDate(t) >= from(dates) AND taskEndDate(t) <= to(dates) AND isDrawing(t)
    PROPERTIES NEWSESSION newDrawingTask() TOOLBAR DRAW t, EDIT(t), DELETE(t)
;

DESIGN drawingSchedule {
    OBJECTS {
        NEW header {
            alignment = STRETCH;
            horizontal = TRUE;
            NEW interval {
                horizontal = TRUE;
                MOVE PROPERTY(prevInterval);
                MOVE PROPERTY(dates);
                MOVE PROPERTY(nextInterval);
                NEW info{
                    alignment = END;
                    MOVE PROPERTY (color);
                }
            }
            
        }
        NEW tabbedPane {
            tabbed = TRUE;
            fill = 1;

            MOVE BOX(tt){
                caption = 'График отрисовки';
                PROPERTY (man){
                    charWidth = 12;
                }
                PROPERTY (des){
                    charWidth = 12;
                    valueClass = 'caption';
                }
                PROPERTY (pro){
                    charWidth = 12;
                }
                PROPERTY(captionTask(d, tt)) {
                    charWidth = 2;
                }
            }
            MOVE BOX (t){
                caption = 'Задачи';
            }
        }
        PROPERTY (edit(tt)){
            changeMouse = 'DBLCLK';
        }
    }
}

NAVIGATOR {
    dashboard {
        NEW drawingSchedule;
    }
}


onStarted() +{
    IF NOT taskType('typeDrawing') THEN NEW t = TaskType{
        id(t) <- 'typeDrawing';
        name(t) <- 'Отрисовка';
    }
}

edit (Task t) + {
    IF type(t) = taskType('typeDrawing') THEN {
        SHOW taskDrawing OBJECTS t = t DOCKED;
    } ELSE {
        SHOW task OBJECTS t = t DOCKED;
    }
}

WHEN LOCAL CHANGED(project(Task t)) DO {
    designer(t) <- designer(project(t));
    assignedTo(t) <- manager(project(t));
}

showAllTasks 'Отображать все задачи' = DATA BOOLEAN (CustomUser);

EXTEND FORM employee
    PROPERTIES(e) showAllTasks
;

DESIGN employee {
    login {
        MOVE PROPERTY(showAllTasks(e));
    }
}

filterTaskUser(Task t) = 
    TRUE IF author(t) == currentUser()
        OR assignedTo(t) == currentUser() 
        OR showAllTasks(currentUser());

EXTEND FORM tasks
    FILTERS filterTaskUser(t)
;
    